-- 코드를 입력하세요
# SELECT CAST(SUBSTRING(DATETIME, 12, 2) AS UNSIGNED) AS HOUR, COUNT(*) AS COUNT
# SELECT EXTRACT(HOUR FROM DATETIME) AS HOUR, COUNT(*) COUNT
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) < 20
GROUP BY 1
ORDER BY 1
